[project]
name = "keepass-fish-history"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pykeepass>=4.1.1.post1",
    "lxml>=6.0.0",
    "pyyaml>=6.0.2",
]

